### ISSUE TITLE
Top bar button shading

### ISSUE THREAD

**Issue by almereyda** [ionutbortis/gnome-bedtime-mode#10]
The shading of the top bar button could indicate the toggle of bedtime mode, similar to what [the lock keys extension](https://extensions.gnome.org/extension/36/lock-keys/) does.

![Bildschirmfoto von 2021-08-25 06-14-50](https://user-images.githubusercontent.com/1645308/130725663-fc3779d1-936a-4806-86dd-bb693296d357.png) ![Bildschirmfoto von 2021-08-25 06-13-32](https://user-images.githubusercontent.com/1645308/130725466-c9dd710d-677e-4b92-959d-e5bd4bfac80c.png)

![Bildschirmfoto von 2021-08-25 06-13-20](https://user-images.githubusercontent.com/1645308/130725471-5b516622-b449-4328-908e-0f49469caff3.png) ![Bildschirmfoto von 2021-08-25 06-15-05](https://user-images.githubusercontent.com/1645308/130725690-ad3c0c4a-5b47-44cd-9575-aebb424e3270.png)

**Comment by ionutbortis** [comment]
Hello,

I actually had it like this, but at that moment I decided that a toggle indicator for the icon is not actually needed and it kinda looks better having the same shading/alpha, imho.

It seems that more people are interested in this so I will implement it in the next release :grin: 

Thanks for the feedback!
