### ISSUE TITLE
Unable to create `po` file for new language

### ISSUE THREAD

**Issue by daPhipz** [ionutbortis/gnome-bedtime-mode#18]
Whenever I try to create a `po` file for a new language, I am getting this error:

```
$ scripts/languages.sh --new-locale=de
/home/philipp/Programming/GNOME Extensions/bedtime-mode/scripts/_vars.sh: Zeile 16: declare: »new_locale de=«: Ist kein gültiger Bezeichner.
Generating extension POT file...
Replacing charset line in order to use UTF-8...
Extension POT file: /home/philipp/Programming/GNOME Extensions/bedtime-mode/po/bedtime-mode.pot
Updating es.po..... fertig.
Updating nl.po.... fertig.
Updating ro.po...... fertig.
```

Do you have an idea what could cause this?

**Comment by ionutbortis** [comment]
Hi Philipp,

Can you check the latest code from the `next-release` branch?

Some double quoting fixes were crashing the code that converts script arguments to script variables in `_vars.sh` file.

I installed German language and keyboard layout and used your project path `~/Programming/GNOME Extensions/bedtime-mode` to run the scripts. All seems fine now on my machine (bash version 5.0.17(1)-release).

**Comment by daPhipz** [comment]
It works now :+1: 
Expect a translation PR in the coming days ;)
